### PR TITLE
Kevin/oof state

### PR DESCRIPTION
**Pull request by NoScopie**
Added OofState DataType
Used in UserOofSettings to set OofState

    $settings = new UserOofSettings();
    $settings->OofState = OofState::SCHEDULED;

### CODE REVIEW

**Comment by adamelso** [comment]
Hi Kevin, thanks for these PRs. So are these classes new, or have they been introduced in the original PHP EWS repository?

Worth mentioning that I'm not really maintaining this fork any longer (perhaps I shall update the README to mention this). See https://github.com/adamelso/php-ews/issues/3 for more info.

**Comment by NoScopie** [comment]
I think they are new in the original PHP EWS repo.

https://github.com/jamesiarmes/php-ews/blob/master/EWSType/OofState.php
I've just added it in this bundle for usage with the already existing UserOofSettings.

I've added them in my own project and everything works as it should be.

**Comment by adamelso** [comment]
Okay, great! I'll merge them :)

**Comment by NoScopie** [comment]
If I encounter more, I'll create them as well. I'll update the bundle in my project and let you know if everything works as it should be.

**Pull request merged**
